// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/sync-types.py
// Source: backend/models/

export type TargetStatus = "pending" | "processing" | "completed" | "failed";

export type TargetType = "video" | "comment" | "user";

export type TaskType = "report_batch" | "autoreply_poll" | "cookie_health_check" | "log_cleanup";

export interface Account {
  name: string;
  sessdata: string;
  bili_jct: string;
  buvid3: string | null;
  buvid4: string | null;
  dedeuserid_ckmd5: string | null;
  refresh_token: string | null;
  group_tag: string | null;
  id: number;
  uid: number | null;
  is_active: boolean;
  last_check_at: string | null;
  status: string;
  created_at: string;
}

export interface AccountBase {
  name: string;
  sessdata: string;
  bili_jct: string;
  buvid3: string | null;
  buvid4: string | null;
  dedeuserid_ckmd5: string | null;
  refresh_token: string | null;
  group_tag: string | null;
}

export interface AccountCreate {
  name: string;
  sessdata: string;
  bili_jct: string;
  buvid3?: string | null;
  buvid4?: string | null;
  dedeuserid_ckmd5?: string | null;
  refresh_token?: string | null;
  group_tag?: string | null;
}

export interface AccountImport {
  name: string;
  sessdata: string;
  bili_jct: string;
  buvid3: string | null;
  buvid4: string | null;
  dedeuserid_ckmd5: string | null;
  group_tag: string | null;
}

export interface AccountPublic {
  id: number;
  name: string;
  uid: number | null;
  buvid3: string | null;
  buvid4: string | null;
  group_tag: string | null;
  is_active: boolean;
  last_check_at: string | null;
  status: string;
  created_at: string;
}

export interface AccountStatus {
  id: number;
  name: string;
  status: string;
  is_valid: boolean;
  uid: number | null;
}

export interface AccountUpdate {
  name?: string | null;
  sessdata?: string | null;
  bili_jct?: string | null;
  buvid3?: string | null;
  buvid4?: string | null;
  dedeuserid_ckmd5?: string | null;
  refresh_token?: string | null;
  group_tag?: string | null;
  is_active?: boolean | null;
}

export interface AutoReplyConfig {
  id: number;
  keyword: string | null;
  response: string;
  priority: number;
  is_active: boolean;
}

export interface AutoReplyConfigBase {
  keyword: string | null;
  response: string;
  priority: number;
}

export interface AutoReplyConfigCreate {
  keyword?: string | null;
  response: string;
  priority?: number;
}

export interface AutoReplyConfigUpdate {
  keyword?: string | null;
  response?: string | null;
  priority?: number | null;
  is_active?: boolean | null;
}

export interface AutoReplyDefaultUpsert {
  response: string;
}

export interface AutoReplyStatus {
  is_running: boolean;
  active_accounts: number;
  last_poll_at: string | null;
}

export interface BatchReportResult {
  total_targets: number;
  total_accounts: number;
  successful: number;
  failed: number;
  results: ReportResult[];
}

export interface CommentScanRequest {
  bvid: string;
  account_id: number;
  reason_id?: number;
  reason_text?: string;
  max_pages?: number;
  auto_report?: boolean;
}

export interface CommentScanResult {
  bvid: string;
  aid: number;
  comments_found: number;
  targets_created: number;
  reports_executed: number;
  reports_successful: number;
  errors: string[];
}

export interface ReportBatchExecuteRequest {
  target_ids?: number[] | null;
  account_ids?: number[] | null;
}

export interface ReportExecuteRequest {
  target_id: number;
  account_ids?: number[] | null;
}

export interface ReportLog {
  id: number;
  target_id: number;
  account_id: number | null;
  account_name: string | null;
  action: string;
  request_data: Record<string, unknown> | null;
  response_data: Record<string, unknown> | null;
  success: boolean;
  error_message: string | null;
  executed_at: string;
}

export interface ReportResult {
  target_id: number;
  account_id: number;
  account_name: string;
  success: boolean;
  message: string;
  response: unknown | null;
}

export interface ScheduledTask {
  name: string;
  task_type: TaskType;
  cron_expression: string | null;
  interval_seconds: number | null;
  config_json: Record<string, unknown> | null;
  id: number;
  is_active: boolean;
  last_run_at: string | null;
}

export interface ScheduledTaskBase {
  name: string;
  task_type: TaskType;
  cron_expression: string | null;
  interval_seconds: number | null;
  config_json: Record<string, unknown> | null;
}

export interface ScheduledTaskCreate {
  name: string;
  task_type: TaskType;
  cron_expression?: string | null;
  interval_seconds?: number | null;
  config_json?: Record<string, unknown> | null;
}

export interface ScheduledTaskUpdate {
  name?: string | null;
  cron_expression?: string | null;
  interval_seconds?: number | null;
  is_active?: boolean | null;
  config_json?: Record<string, unknown> | null;
}

export interface Target {
  type: TargetType;
  identifier: string;
  aid: number | null;
  reason_id: number | null;
  reason_content_id: number | null;
  reason_text: string | null;
  display_text: string | null;
  id: number;
  status: TargetStatus;
  retry_count: number;
  created_at: string;
  updated_at: string | null;
}

export interface TargetBase {
  type: TargetType;
  identifier: string;
  aid: number | null;
  reason_id: number | null;
  reason_content_id: number | null;
  reason_text: string | null;
  display_text: string | null;
}

export interface TargetBatchCreate {
  type: TargetType;
  identifiers: string[];
  reason_id?: number | null;
  reason_content_id?: number | null;
  reason_text?: string | null;
}

export interface TargetCreate {
  type: TargetType;
  identifier: string;
  aid?: number | null;
  reason_id?: number | null;
  reason_content_id?: number | null;
  reason_text?: string | null;
  display_text?: string | null;
}

export interface TargetListResponse {
  items: Target[];
  total: number;
  page: number;
  page_size: number;
}

export interface TargetUpdate {
  reason_id?: number | null;
  reason_content_id?: number | null;
  reason_text?: string | null;
  status?: TargetStatus | null;
}
